### ISSUE TITLE
Display the correct currency format

### ISSUE THREAD

**Issue by matheusturmina** [rssnyder/discord-stock-ticker#89]
When i modify a cryptobot currency, it still show the "usd" format for different currency.

In brl should be R$50,00, but is showing $50.00 for example.

A nice feature would be customize the currency format like we are able to customize the "ticker" nickname.

**Comment by rssnyder** [comment]
@matheusturmina this is actually a case of bad documentation. This is a current feature but I forgot to add it to the README.

See the implementation here: https://github.com/rssnyder/discord-stock-ticker/blob/master/ticker_request.go#L23

This will be fixed in v3.5.0 that will be releasing tomorrow afternoon. You can view it using the latest beta release: https://github.com/rssnyder/discord-stock-ticker/tree/feat/state#add-a-new-bot

**Comment by matheusturmina** [comment]
Nice! Worked like a charm, thanks!
